### ISSUE TITLE
Random hang when ingesting AATSR.  Looks like data does ingest but hangs after giving message ingestion complete

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#1]
% AATSR_GET_HEADERS: Unknown file type 'TOA_1C'. Trying 'TOA_1P'
% LOADCT: Loading table Rainbow + white
% Loaded DLM: NCDF.
% Program caused arithmetic error: Floating divide by 0
% Program caused arithmetic error: Floating illegal operand

**Comment by MArias2014** [comment]
So far I had no issues ingesting AATSR data in nDIMITRI 4, so I propose to close the topic until having the mentioned issue again.
