### ISSUE TITLE
Hard-coded numerical constants

### ISSUE THREAD

**Issue by cmazeran** [dimitri-argans/DIMITRI#10]
Some numerical constants are hard-coded, e.g:
In  RECAL/RECALIBRATE_DOUBLETS.PRO
 SEN_UNCERTR = 0.03
 SEN_UNCERTS = 0.03

In vicarious and recal: REF_O3=300, other similar meto data

This may introduce big mistakes in future developments, when constants are defined and used in different routines.

They should be defined in new auxiliary data. For uncertainty, could be sensor depend (SNR ?....)

**Comment by MArias2014** [comment]
Not sure if this is still a problem in DIMITRI 4. I propose to close it, as a topic was open in JIRA bout this particular issue.
