### ISSUE TITLE
Clean DB for duplicates

### ISSUE THREAD

**Issue by cmazeran** [dimitri-argans/DIMITRI#11]
There are duplicated products in the DB (in DIMITRI_DATABASE.CSV and .SAV) because of duplicated/overlapping L1 raw data. Example:
Site_Libya4/MERIS/Proc_3rd_Reprocessing/2003/ 20030818
This may produce unwanted behaviour (like getting an array instead of scalar with function WHERE) and bias the statistics.

Automatic cleaning could consist in:
- Identify duplicates with IDL (use UNIQ function)
- Choose the best product (highest ROI coverage) 
- Remove physically the other products : remove L1 in raw data, remove RGB in Input folder
- Update CSV and SAV files

**Comment by MArias2014** [comment]
An automatic clean routine would be nice, as proposed here, but this is not an issue, just further development. We can discuss this , anyway.
