### ISSUE TITLE
Maximum number of columns in CSV ouputs

### ISSUE THREAD

**Issue by cmazeran** [dimitri-argans/DIMITRI#12]
Some CSV outputs are written with line=parameters x column=obs, instead of the classical ordering column=parameters x line = obs (like in DIMITRI_DATABASE.CSV)
This concerns for instance output of VGT simulations: SIM_SITE_VEGETATION_Calibration_1.CSV
The problem is that in general there are much more obs than params, and Excel 2003 cannot open more than 256 column, LibreOffice Calc 4 no more than 1024 (extended for more recent version)
Probably it would be better to harmonise all outputs with same ordering and columns for parameters.

**Comment by MArias2014** [comment]
VGT simulation is no longer supported by DIMITRI. This enhancement is not required anymore and should be closed. A JIRA action has been included to verify the named issue, if for any chances happen in other outputs.

**Comment by MArias2014** [comment]
From Excel 2010 the maximum number of columns is 16,384. This issue can be closed.
