### ISSUE TITLE
Wavelength mess in gas transmittance computation (not bug)

### ISSUE THREAD

**Issue by cmazeran** [dimitri-argans/DIMITRI#13]
There is a mess in each toa_simulation/get...transmission.pro routines by calling the misc/extract_dimitri_rsr routine.

While get...transmission should simply interpolate aux data to given wavelengths, the call to extract_dimitri_rsr makes an intermediate interpolation at 0.5nm. It is useless and can just introduce errors.

Then the way transmittance are spectrally integrated in toa_simulation/vgt_simulation.pro is uselessly complex, also by introducing a 0.5nm array instead of directly using the bands of RSR data. This could be simplified as in new drift_monitoring.pro routine.

**Comment by MArias2014** [comment]
Duplicated issue and already included in JIRA. Please close this one.
