### ISSUE TITLE
Unconsistency between DB and DAT files

### ISSUE THREAD

**Issue by cmazeran** [dimitri-argans/DIMITRI#14]
Some acquisitions are in the .dat files and do have RGB but they are not stored in the CSV DB file. Examples for  Site_Libya4/MERIS/Proc_3rd_Reprocessing (in decimal year):
       2006.7051
       2006.8393
       2006.9434
       2007.0640
       2007.0887
       2007.1270
       2007.1599
       2007.1708
       2007.1846
       2007.1873
       2007.3352
       2009.0997
This already happens in the DIMITRI_2.0 version currently delivered to users.
Maybe this will be solved with new ingestion over Libya4? A consistency check between .CSV and all .DAT would be salutary.

**Comment by MArias2014** [comment]
Related to the mentioned problem when DIMITRI crashes at some point of the ingestion: It generates the files before updating the DB, so any crash originates files that need to be removed by hand to avoid further issues in the future.

**Comment by MBouvet** [comment]
This will not be an issue in DIMITRI V4 anymore. We give up on this one.
