### ISSUE TITLE
Missing info on number of pixels per direction

### ISSUE THREAD

**Issue by cmazeran** [dimitri-argans/DIMITRI#15]
For multidirectional sensors (AATSR, etc.), there is no way to know what is the number of pixels per direction. The CSV DB file only mentions by NUM_ROI_PX the maximum number reached for one direction (itself unknown). But this number is different for each directions. 

Hence the pixel-by-pixel extractions can hardly be correctly used when we need to distinguish the directions (case of cloud screening with spatial standard-deviation).

Ideally the averaged extraction .dat files could have this info as a new field (which would be redundant with NUM_ROI_PX for unidirectional sensors). Or alternatively, the pixel-by-pixel extraction .dat files could have the index of the directions as new field (which would be always 0 for unidirectional sensors).

A solution if one doesn't want to do re-ingestion would be to restore together the averaged and pixel-by-pixel extractions, and search the number of pixels by averaging on a sliding window, until the averaged value is found...

Pb is mainly for PARASOL on its 16 direction; for AATSR and ATSR2 with 2 direction, NUM_ROI_PX is enough to compute the number in the other direction

**Comment by MArias2014** [comment]
This was solved in DIMITRI 4 as the output is now in netCDF format, with a layer of data per viewing angle. One of the variables associated to each angle is the number of pixels. This issue can be closed.
