### ISSUE TITLE
Ingesting MERIS data over DomeC crashes DIMITRI

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#20]
Ingesting MERIS 3rd reproc over domeC for the year 2008 causes the following error

% XMANAGER: Caught unexpected error from client application. Message follows...
% NCDF_CONTROL: Attempt to take the file out of define mode (ENDEF) failed. (NC_ERROR=-31)
% Execution halted at:  WRITE_DIMITRI_EXTRACT_TOA_NCDF
%                       DIMITRI_INTERFACE_EXTRACT_TOA_NCDF
%                       INGEST_MERIS_PRODUCT
%                       DIMITRI_INTERFACE_INGEST
%                       DHMI_INGEST_PROCESS
%                       XMANAGER_EVLOOP_STANDARD
%                       XMANAGER        
%                       DIMITRI_V3      
%                       IDLRTMAIN       
%                       $MAIN$

**Comment by MArias2014** [comment]
Probably no longer a problem. I will ingest MERIS DomeC data to confirm or discard this issue.
