### ISSUE TITLE
Ingesting MERIS data over SIO causes crash

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#22]
After a couple of hours DIMITRI crashes with the error below.  This seems to be the first file  so DIMITRI must be doing a long loop before beginning the ingestion process.

===================================================================

% XMANAGER: Caught unexpected error from client application. Message follows...
% READU: Error encountered reading from file. Unit: 100
         File: /home/dmarrable/DIMITRI_3.0/Input/Site_SIO/MERIS/Proc_3rd_Reprocessing/2002/MER_RR__1PN
         MAP20021017_035550_000001892010_00233_03293_0001.N1
 
% Execution halted at:  GET_MERIS_L1B_RADIANCE
%                       GET_MERIS_QUICKLOOK
%                       INGEST_MERIS_PRODUCT
%                       DIMITRI_INTERFACE_INGEST
%                       DHMI_INGEST_PROCESS
%                       XMANAGER_EVLOOP_STANDARD
%                       XMANAGER        
%                       DIMITRI_V3      
%                       IDLRTMAIN       
%                       $MAIN$

**Comment by MArias2014** [comment]
Probably not a problem anymore. I will ingest data over SIO later to check this.
