### ISSUE TITLE
BRDF Cloudscreening returns error bout ROI in trainng set even though the training file does contain data within the ROI

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#23]
BRDF_CLOUD_SCREENING: WARNING, NO SENSOR DATA FOUND WITHIN PIXEL THRESHOLD CONDITION IN CLOUD TRAINING DB, RETURN

**Comment by MArias2014** [comment]
Well, this is the same bug than for SSV, or closely related. Moved to JIRA.
