### ISSUE TITLE
SSV Cloudscreening returns error bout ROI in trainng set even though the training file does contain data within the ROI

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#24]
SSV_CLOUD_SCREENING: WARNING, NO SENSOR DATA FOUND WITHIN PIXEL THRESHOLD CONDITION IN CLOUD TRAINING DB, RETURN

It would be helpful to add the entry that it has an issue with the cs log

**Comment by MArias2014** [comment]
Maybe Bahjat has an idea about this. In any case, to check and correct in QA4EO. Moved to JIRA.
