### ISSUE TITLE
Cloud selection issue

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#28]
Conditions like « DB_DATA.AUTO_CS LE CP_LIMIT » do not work when DB_DATA.AUTO_CS= CP_LIMIT, surely because of float data (observed in real case) ; to be replace by ABS( DB_DATA.AUTO_CS – CP_LIMIT) LT TOL with TOL=0.000..1

**Comment by MArias2014** [comment]
Probably open. To check. Moved to JIRA.
