### ISSUE TITLE
Unconsistent VGT simulation (?)

### ISSUE THREAD

**Issue by cmazeran** [dimitri-argans/DIMITRI#3]
VGT simulations need first to have run the "Sensor recal" twice, with MERIS and AATSR as reference, and then use super sensor files
Output/RECALIBRATION/SSEN_SITE_REF_MERIS_PROC_BAND.DAT  and Output/RECALIBRATION/SSEN_SITE_REF_AATSR_PROC_BAND.DAT
However these super sensor files depend on the calibrated sensor choosen during "Sensor recal", so at the end the VGT simulation depends on other sensors than just MERIS and AASTR ! Example shown below when "Sensor recal." is run for recalibrating PARASOL or MERIS 2nd reproc. 
I'm not sure this dependence is on purpose - at least it's not written in the SUM. Rigorously VGT simulations should only use data from  MERIS and AASTR.
I've the same problem for BRDF drift if I want to use existing routines :-/

![vgt_sim_rho](https://f.cloud.github.com/assets/5501978/2027992/bba9987e-88c5-11e3-86ac-b25b836f637f.JPG)
![vgt_sim_rho](https://f.cloud.github.com/assets/5501978/2027995/c594fa36-88c5-11e3-8114-f5c9e739aa28.JPG)

**Comment by MArias2014** [comment]
VEGETATION simulation is no longer supported in DIMITRI. This issue should be closed.
