### ISSUE TITLE
ingest_aatsr_product.pro:

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#33]
SF = TEMP_REF/MEAN(TOA_REF(ROI_INDEX)) it should be SF = TEMP_REF/MEAN(TOA_REF(ROI_INDEX[VALID])) because the drift correction is multiplicative and TEMP_REF is only for VALID pixel.

**Comment by MArias2014** [comment]
To verify if this was implemented or not, and fix if required. Moved to JIRA.
