### ISSUE TITLE
Type Conversion error

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#37]
Error message when adding new data to existing: Unable to convert given STRING to Byte. % Detected at: DIMITRI_INTERFACE_EXTRACT_TOA_NCDF 81 Source/misc/dimitri_interface_extract_toa_ncdf.pro

**Comment by MArias2014** [comment]
Probvably deprecated, as the netCDF functionalities were rebuilt in DIMITRI 4. To confirm. Moved to JIRA.
