### ISSUE TITLE
Transmittance computation 

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#39]
unnecessarily complex, leading to longer processing time. There is a mess in each toa_simulation/get...transmission.pro routines by calling the misc/extract_dimitri_rsr routine. While get...transmission should simply interpolate aux data to given wavelengths, the call to extract_dimitri_rsr makes an intermediate interpolation at 0.5nm. It is useless and can just introduce errors.  Then the way transmittance are spectrally integrated in toa_simulation/vgt_simulation.pro is uselessly complex, also by introducing a 0.5nm array instead of directly using the bands of RSR data. This could be simplified as in new drift_monitoring.pro routine.

**Comment by MArias2014** [comment]
First part of the issue needs review. The second part related to VGT simulation is no longer required, as that module is deprecated. First par has been moved to JIRA.
