### ISSUE TITLE
Changes to be done to the HMI of DIMITRI V4

### ISSUE THREAD

**Issue by MBouvet** [dimitri-argans/DIMITRI#47]
The title of the pop up that comes when one hits the 'Rayleigh ARG' or 'Rayleigh MAG' button should be 'DIMITRI V4.0: RAYLEIGH SIMULATION' rather that 'RAYLEIGH CALIBRATION' . DIMITRI is not meant to perform calibration of the sensors... it is meant just to assesss their calibration.

Same modification should be applied to the GLINT and DESERT methodologies pop-ups

**Comment by ncamlong** [comment]
In all HMI function linked to sensor to simulation comparison process, the "CALIBRATION" word has been replaced by the "SIMULATION" word. The "CAL" abbreviation has been replaced by the "SIMU" abbreviation.
