### ISSUE TITLE
GIT commit version should be queryable from the GUI to tell which code revisions the code is based on.

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#9]
There is ambiguity between the code version and that 'database' version.  I propose that V2.0, V3.0 refer to the project or the database version and based of major code milestones.  But this does not capture the version that the code is based on.  

So when code is updated with a bug fix, it would be useful to determine if the user's version is up to date.

**Comment by MArias2014** [comment]
This is more related to organization of the project than to the software itself. We can discuss this, but clearly not a software matter. Please, close the issue.
